export default {
  id: 'L6-EX1',
  levelId: 6,
  order: 1,
  titleKey: 'level6.ex1.title',
  storyKey: 'level6.ex1.story',
  steps: ['level6.ex1.step1', 'level6.ex1.step2', 'level6.ex1.step3', 'level6.ex1.step4'],
  hints: ['level6.ex1.hint1', 'level6.ex1.hint2'],
  initialData: [
    {
      name: 'Sheet1',
      order: 0,
      row: 14,
      column: 3,
      celldata: [
        { r: 0, c: 0, v: { v: 'Fach', m: 'Fach', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 0, c: 1, v: { v: 'Note', m: 'Note', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 0, c: 2, v: { v: 'Punkte (%)', m: 'Punkte (%)', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 1, c: 0, v: { v: 'Mathematik', m: 'Mathematik', ct: { fa: 'General', t: 's' } } },
        { r: 2, c: 0, v: { v: 'Deutsch', m: 'Deutsch', ct: { fa: 'General', t: 's' } } },
        { r: 3, c: 0, v: { v: 'Englisch', m: 'Englisch', ct: { fa: 'General', t: 's' } } },
        { r: 4, c: 0, v: { v: 'BWL', m: 'BWL', ct: { fa: 'General', t: 's' } } },
        { r: 5, c: 0, v: { v: 'IT', m: 'IT', ct: { fa: 'General', t: 's' } } },
        { r: 7, c: 0, v: { v: 'Durchschnitt', m: 'Durchschnitt', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 8, c: 0, v: { v: 'Beste Note', m: 'Beste Note', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 9, c: 0, v: { v: 'Schlechteste Note', m: 'Schlechteste Note', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 10, c: 0, v: { v: 'Notenspanne', m: 'Notenspanne', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 12, c: 0, v: { v: 'Ø Punkte', m: 'Ø Punkte', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 13, c: 0, v: { v: 'Max. Punkte', m: 'Max. Punkte', ct: { fa: 'General', t: 's' }, bl: 1 } },
      ],
      config: { columnlen: { 0: 150, 1: 80, 2: 100 } },
    },
  ],
  lockedCells: [
    { r: 0, c: 0 }, { r: 0, c: 1 }, { r: 0, c: 2 },
    { r: 1, c: 0 }, { r: 2, c: 0 }, { r: 3, c: 0 }, { r: 4, c: 0 }, { r: 5, c: 0 },
    { r: 7, c: 0 }, { r: 8, c: 0 }, { r: 9, c: 0 }, { r: 10, c: 0 },
    { r: 12, c: 0 }, { r: 13, c: 0 },
  ],
  ui: { showToolbar: false, showFormulaBar: true, showSheetTabs: false },
  xp: { base: 50, bonus: 20 },
  validations: [
    { type: 'cellValue', cell: { r: 1, c: 1 }, expected: 2, stepIndex: 0 },
    { type: 'cellValue', cell: { r: 1, c: 2 }, expected: 85, stepIndex: 0 },
    { type: 'cellValue', cell: { r: 2, c: 1 }, expected: 3, stepIndex: 0 },
    { type: 'cellValue', cell: { r: 2, c: 2 }, expected: 72, stepIndex: 0 },
    { type: 'cellValue', cell: { r: 3, c: 1 }, expected: 1, stepIndex: 0 },
    { type: 'cellValue', cell: { r: 3, c: 2 }, expected: 91, stepIndex: 0 },
    { type: 'cellValue', cell: { r: 4, c: 1 }, expected: 3, stepIndex: 0 },
    { type: 'cellValue', cell: { r: 4, c: 2 }, expected: 68, stepIndex: 0 },
    { type: 'cellValue', cell: { r: 5, c: 1 }, expected: 2, stepIndex: 0 },
    { type: 'cellValue', cell: { r: 5, c: 2 }, expected: 80, stepIndex: 0 },
    { type: 'cellFormula', cell: { r: 7, c: 1 }, expected: 'MITTELWERT(B2:B6)', stepIndex: 1 },
    { type: 'cellFormula', cell: { r: 8, c: 1 }, expected: 'MIN(B2:B6)', stepIndex: 2 },
    { type: 'cellFormula', cell: { r: 9, c: 1 }, expected: 'MAX(B2:B6)', stepIndex: 2 },
    { type: 'cellFormula', cell: { r: 10, c: 1 }, expected: 'B10-B9', stepIndex: 2 },
    { type: 'cellFormula', cell: { r: 12, c: 2 }, expected: 'MITTELWERT(C2:C6)', stepIndex: 3 },
    { type: 'cellFormula', cell: { r: 13, c: 2 }, expected: 'MAX(C2:C6)', stepIndex: 3 },
  ],
};
