export default {
  id: 'A-L6-EX2',
  trackId: 'avm',
  levelId: 6,
  order: 2,
  titleKey: 'level6.ex2.title',
  storyKey: 'level6.ex2.story',
  steps: ['level6.ex2.step1', 'level6.ex2.step2', 'level6.ex2.step3', 'level6.ex2.step4'],
  hints: ['level6.ex2.hint1', 'level6.ex2.hint2'],
  initialData: [
    {
      name: 'Sheet1',
      order: 0,
      row: 14,
      column: 3,
      celldata: [
        { r: 0, c: 0, v: { v: 'Gehaltsrechner', m: 'Gehaltsrechner', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 0, c: 1, v: { v: 'Wert', m: 'Wert', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 1, c: 0, v: { v: 'Stundenlohn (€)', m: 'Stundenlohn (€)', ct: { fa: 'General', t: 's' } } },
        { r: 2, c: 0, v: { v: 'Stunden/Woche', m: 'Stunden/Woche', ct: { fa: 'General', t: 's' } } },
        { r: 3, c: 0, v: { v: 'Wochen/Monat', m: 'Wochen/Monat', ct: { fa: 'General', t: 's' } } },
        { r: 3, c: 1, v: { v: 4, m: '4', ct: { fa: 'General', t: 'n' } } },
        { r: 5, c: 0, v: { v: 'Wochenlohn (€)', m: 'Wochenlohn (€)', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 6, c: 0, v: { v: 'Monatslohn (€)', m: 'Monatslohn (€)', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 7, c: 0, v: { v: 'Jahreslohn (€)', m: 'Jahreslohn (€)', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 9, c: 0, v: { v: 'Sozialabgaben (20%)', m: 'Sozialabgaben (20%)', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 10, c: 0, v: { v: 'Netto/Monat (€)', m: 'Netto/Monat (€)', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 12, c: 0, v: { v: 'Netto/Tag (€)', m: 'Netto/Tag (€)', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 13, c: 0, v: { v: 'Netto/Stunde (€)', m: 'Netto/Stunde (€)', ct: { fa: 'General', t: 's' }, bl: 1 } },
      ],
      config: { columnlen: { 0: 170, 1: 120, 2: 100 } },
    },
  ],
  lockedCells: [
    { r: 0, c: 0 }, { r: 0, c: 1 },
    { r: 1, c: 0 }, { r: 2, c: 0 }, { r: 3, c: 0 }, { r: 3, c: 1 },
    { r: 5, c: 0 }, { r: 6, c: 0 }, { r: 7, c: 0 },
    { r: 9, c: 0 }, { r: 10, c: 0 },
    { r: 12, c: 0 }, { r: 13, c: 0 },
  ],
  ui: { showToolbar: false, showFormulaBar: true, showSheetTabs: false },
  xp: { base: 55, bonus: 20 },
  validations: [
    { type: 'cellValue', cell: { r: 1, c: 1 }, expected: 12.5, stepIndex: 0 },
    { type: 'cellValue', cell: { r: 2, c: 1 }, expected: 20, stepIndex: 0 },
    { type: 'cellFormula', cell: { r: 5, c: 1 }, expected: 'B2*B3', stepIndex: 1 },
    { type: 'cellFormula', cell: { r: 6, c: 1 }, expected: 'B6*B4', stepIndex: 1 },
    { type: 'cellFormula', cell: { r: 7, c: 1 }, expected: 'B7*12', stepIndex: 2 },
    { type: 'cellFormula', cell: { r: 9, c: 1 }, expected: 'B7*0.2', stepIndex: 2 },
    { type: 'cellFormula', cell: { r: 10, c: 1 }, expected: 'B7-B10', stepIndex: 2 },
    { type: 'cellFormula', cell: { r: 12, c: 1 }, expected: 'B11/22', stepIndex: 3 },
    { type: 'cellFormula', cell: { r: 13, c: 1 }, expected: 'B11/B3/B4', stepIndex: 3 },
  ],
};
