export default {
  id: 'K-L1-EX1',
  trackId: 'kaufleute',
  levelId: 1,
  order: 1,
  titleKey: 'kaufleute.level1.ex1.title',
  storyKey: 'kaufleute.level1.ex1.story',
  steps: [
    'kaufleute.level1.ex1.step1',
    'kaufleute.level1.ex1.step2',
    'kaufleute.level1.ex1.step3',
    'kaufleute.level1.ex1.step4',
  ],
  hints: ['kaufleute.level1.ex1.hint1', 'kaufleute.level1.ex1.hint2'],
  initialData: [
    {
      name: 'Sheet1',
      order: 0,
      row: 10,
      column: 5,
      celldata: [
        { r: 0, c: 0, v: { v: 'Artikel', m: 'Artikel', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 0, c: 1, v: { v: 'Netto (EUR)', m: 'Netto (EUR)', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 0, c: 2, v: { v: 'MwSt-Faktor', m: 'MwSt-Faktor', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 0, c: 3, v: { v: 'Brutto (EUR)', m: 'Brutto (EUR)', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 1, c: 2, v: { v: 1.19, m: '1,19', ct: { fa: 'General', t: 'n' } } },
        { r: 1, c: 0, v: { v: 'Ordner', m: 'Ordner', ct: { fa: 'General', t: 's' } } },
        { r: 2, c: 0, v: { v: 'Papier', m: 'Papier', ct: { fa: 'General', t: 's' } } },
        { r: 3, c: 0, v: { v: 'Stifte', m: 'Stifte', ct: { fa: 'General', t: 's' } } },
        { r: 4, c: 0, v: { v: 'Kleber', m: 'Kleber', ct: { fa: 'General', t: 's' } } },
        { r: 1, c: 1, v: { v: 4.99, m: '4,99', ct: { fa: 'General', t: 'n' } } },
        { r: 2, c: 1, v: { v: 3.49, m: '3,49', ct: { fa: 'General', t: 'n' } } },
        { r: 3, c: 1, v: { v: 7.99, m: '7,99', ct: { fa: 'General', t: 'n' } } },
        { r: 4, c: 1, v: { v: 2.49, m: '2,49', ct: { fa: 'General', t: 'n' } } },
      ],
      config: { columnlen: { 0: 120, 1: 110, 2: 120, 3: 120 } },
    },
  ],
  lockedCells: [
    { r: 0, c: 0 }, { r: 0, c: 1 }, { r: 0, c: 2 }, { r: 0, c: 3 },
    { r: 1, c: 0 }, { r: 2, c: 0 }, { r: 3, c: 0 }, { r: 4, c: 0 },
    { r: 1, c: 1 }, { r: 2, c: 1 }, { r: 3, c: 1 }, { r: 4, c: 1 },
    { r: 1, c: 2 },
  ],
  ui: { showToolbar: false, showFormulaBar: true, showSheetTabs: false },
  xp: { base: 30, bonus: 10 },
  validations: [
    { type: 'cellFormula', cell: { r: 1, c: 3 }, expected: 'B2*$C$2', stepIndex: 0 },
    { type: 'cellFormula', cell: { r: 2, c: 3 }, expected: 'B3*$C$2', stepIndex: 1 },
    { type: 'cellFormula', cell: { r: 3, c: 3 }, expected: 'B4*$C$2', stepIndex: 2 },
    { type: 'cellFormula', cell: { r: 4, c: 3 }, expected: 'B5*$C$2', stepIndex: 3 },
  ],
};
