export default {
  id: 'K-L2-EX2',
  trackId: 'kaufleute',
  levelId: 2,
  order: 2,
  titleKey: 'kaufleute.level2.ex2.title',
  storyKey: 'kaufleute.level2.ex2.story',
  steps: [
    'kaufleute.level2.ex2.step1',
    'kaufleute.level2.ex2.step2',
    'kaufleute.level2.ex2.step3',
    'kaufleute.level2.ex2.step4',
  ],
  hints: ['kaufleute.level2.ex2.hint1', 'kaufleute.level2.ex2.hint2'],
  initialData: [
    {
      name: 'Sheet1',
      order: 0,
      row: 8,
      column: 4,
      celldata: [
        { r: 0, c: 0, v: { v: 'Rechnung', m: 'Rechnung', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 0, c: 1, v: { v: 'Betrag (EUR)', m: 'Betrag (EUR)', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 0, c: 2, v: { v: 'Tage bis Zahlung', m: 'Tage bis Zahlung', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 0, c: 3, v: { v: 'Skontobetrag (EUR)', m: 'Skontobetrag (EUR)', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 1, c: 0, v: { v: 'RE-2024-011', m: 'RE-2024-011', ct: { fa: 'General', t: 's' } } },
        { r: 1, c: 1, v: { v: 500, m: '500', ct: { fa: 'General', t: 'n' } } },
        { r: 1, c: 2, v: { v: 7, m: '7', ct: { fa: 'General', t: 'n' } } },
        { r: 2, c: 0, v: { v: 'RE-2024-012', m: 'RE-2024-012', ct: { fa: 'General', t: 's' } } },
        { r: 2, c: 1, v: { v: 320, m: '320', ct: { fa: 'General', t: 'n' } } },
        { r: 2, c: 2, v: { v: 14, m: '14', ct: { fa: 'General', t: 'n' } } },
        { r: 3, c: 0, v: { v: 'RE-2024-013', m: 'RE-2024-013', ct: { fa: 'General', t: 's' } } },
        { r: 3, c: 1, v: { v: 750, m: '750', ct: { fa: 'General', t: 'n' } } },
        { r: 3, c: 2, v: { v: 10, m: '10', ct: { fa: 'General', t: 'n' } } },
        { r: 4, c: 0, v: { v: 'RE-2024-014', m: 'RE-2024-014', ct: { fa: 'General', t: 's' } } },
        { r: 4, c: 1, v: { v: 180, m: '180', ct: { fa: 'General', t: 'n' } } },
        { r: 4, c: 2, v: { v: 20, m: '20', ct: { fa: 'General', t: 'n' } } },
        { r: 5, c: 0, v: { v: 'RE-2024-015', m: 'RE-2024-015', ct: { fa: 'General', t: 's' } } },
        { r: 5, c: 1, v: { v: 960, m: '960', ct: { fa: 'General', t: 'n' } } },
        { r: 5, c: 2, v: { v: 5, m: '5', ct: { fa: 'General', t: 'n' } } },
      ],
      config: { columnlen: { 0: 130, 1: 110, 2: 140, 3: 150 } },
    },
  ],
  lockedCells: [
    { r: 0, c: 0 }, { r: 0, c: 1 }, { r: 0, c: 2 }, { r: 0, c: 3 },
    { r: 1, c: 0 }, { r: 1, c: 1 }, { r: 1, c: 2 },
    { r: 2, c: 0 }, { r: 2, c: 1 }, { r: 2, c: 2 },
    { r: 3, c: 0 }, { r: 3, c: 1 }, { r: 3, c: 2 },
    { r: 4, c: 0 }, { r: 4, c: 1 }, { r: 4, c: 2 },
    { r: 5, c: 0 }, { r: 5, c: 1 }, { r: 5, c: 2 },
  ],
  ui: { showToolbar: false, showFormulaBar: true, showSheetTabs: false },
  xp: { base: 38, bonus: 12 },
  validations: [
    { type: 'cellFormula', cell: { r: 1, c: 3 }, expected: 'IF(C2<=10,B2*0.02,0)', stepIndex: 1 },
    { type: 'cellFormula', cell: { r: 2, c: 3 }, expected: 'IF(C3<=10,B3*0.02,0)', stepIndex: 2 },
    { type: 'cellFormula', cell: { r: 3, c: 3 }, expected: 'IF(C4<=10,B4*0.02,0)', stepIndex: 2 },
    { type: 'cellFormula', cell: { r: 4, c: 3 }, expected: 'IF(C5<=10,B5*0.02,0)', stepIndex: 2 },
    { type: 'cellFormula', cell: { r: 5, c: 3 }, expected: 'IF(C6<=10,B6*0.02,0)', stepIndex: 3 },
  ],
};
