export default {
  id: 'A-L3-EX1',
  trackId: 'avm',
  levelId: 3,
  order: 1,
  titleKey: 'level3.ex1.title',
  storyKey: 'level3.ex1.story',
  steps: ['level3.ex1.step1', 'level3.ex1.step2', 'level3.ex1.step3', 'level3.ex1.step4'],
  hints: ['level3.ex1.hint1', 'level3.ex1.hint2'],
  initialData: [
    {
      name: 'Sheet1',
      order: 0,
      row: 10,
      column: 5,
      celldata: [
        { r: 0, c: 0, v: { v: 'Zutat', m: 'Zutat', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 0, c: 1, v: { v: 'Menge (2 Pers.)', m: 'Menge (2 Pers.)', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 0, c: 2, v: { v: 'Faktor', m: 'Faktor', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 0, c: 3, v: { v: 'Menge (neu)', m: 'Menge (neu)', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 1, c: 0, v: { v: 'Nudeln (g)', m: 'Nudeln (g)', ct: { fa: 'General', t: 's' } } },
        { r: 1, c: 1, v: { v: 200, m: '200', ct: { fa: 'General', t: 'n' } } },
        { r: 2, c: 0, v: { v: 'Tomatensoße (ml)', m: 'Tomatensoße (ml)', ct: { fa: 'General', t: 's' } } },
        { r: 2, c: 1, v: { v: 150, m: '150', ct: { fa: 'General', t: 'n' } } },
        { r: 3, c: 0, v: { v: 'Käse (g)', m: 'Käse (g)', ct: { fa: 'General', t: 's' } } },
        { r: 3, c: 1, v: { v: 50, m: '50', ct: { fa: 'General', t: 'n' } } },
        { r: 4, c: 0, v: { v: 'Öl (EL)', m: 'Öl (EL)', ct: { fa: 'General', t: 's' } } },
        { r: 4, c: 1, v: { v: 1, m: '1', ct: { fa: 'General', t: 'n' } } },
      ],
      config: { columnlen: { 0: 150, 1: 130, 2: 80, 3: 120 } },
    },
  ],
  lockedCells: [
    { r: 0, c: 0 }, { r: 0, c: 1 }, { r: 0, c: 2 }, { r: 0, c: 3 },
    { r: 1, c: 0 }, { r: 1, c: 1 },
    { r: 2, c: 0 }, { r: 2, c: 1 },
    { r: 3, c: 0 }, { r: 3, c: 1 },
    { r: 4, c: 0 }, { r: 4, c: 1 },
  ],
  ui: { showToolbar: false, showFormulaBar: true, showSheetTabs: false },
  xp: { base: 25, bonus: 10 },
  validations: [
    { type: 'cellValue', cell: { r: 1, c: 2 }, expected: 2, stepIndex: 0 },
    { type: 'cellFormula', cell: { r: 1, c: 3 }, expected: 'B2*C2', stepIndex: 1 },
    { type: 'cellFormula', cell: { r: 2, c: 3 }, expected: 'B3*C3', stepIndex: 2 },
    { type: 'cellFormula', cell: { r: 3, c: 3 }, expected: 'B4*C4', stepIndex: 3 },
  ],
};
