export default {
  id: 'L5-EX3',
  levelId: 5,
  order: 3,
  titleKey: 'level5.ex3.title',
  storyKey: 'level5.ex3.story',
  steps: ['level5.ex3.step1', 'level5.ex3.step2', 'level5.ex3.step3', 'level5.ex3.step4'],
  hints: ['level5.ex3.hint1', 'level5.ex3.hint2'],
  initialData: [
    {
      name: 'Sheet1',
      order: 0,
      row: 12,
      column: 5,
      celldata: [
        { r: 0, c: 0, v: { v: 'Zimmertyp', m: 'Zimmertyp', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 0, c: 1, v: { v: 'Preis/Nacht (€)', m: 'Preis/Nacht (€)', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 0, c: 2, v: { v: 'Nächte', m: 'Nächte', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 0, c: 3, v: { v: 'Anzahl Zimmer', m: 'Anzahl Zimmer', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 0, c: 4, v: { v: 'Kosten (€)', m: 'Kosten (€)', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 1, c: 0, v: { v: 'Einzelzimmer', m: 'Einzelzimmer', ct: { fa: 'General', t: 's' } } },
        { r: 1, c: 1, v: { v: 45, m: '45', ct: { fa: 'General', t: 'n' } } },
        { r: 2, c: 0, v: { v: 'Doppelzimmer', m: 'Doppelzimmer', ct: { fa: 'General', t: 's' } } },
        { r: 2, c: 1, v: { v: 65, m: '65', ct: { fa: 'General', t: 'n' } } },
        { r: 3, c: 0, v: { v: 'Dreibettzimmer', m: 'Dreibettzimmer', ct: { fa: 'General', t: 's' } } },
        { r: 3, c: 1, v: { v: 80, m: '80', ct: { fa: 'General', t: 'n' } } },
        { r: 5, c: 0, v: { v: 'Zimmer gesamt', m: 'Zimmer gesamt', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 6, c: 0, v: { v: 'Kosten gesamt', m: 'Kosten gesamt', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 7, c: 0, v: { v: 'Ø Kosten/Zimmer', m: 'Ø Kosten/Zimmer', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 8, c: 0, v: { v: 'Günstigstes/Nacht', m: 'Günstigstes/Nacht', ct: { fa: 'General', t: 's' }, bl: 1 } },
      ],
      config: { columnlen: { 0: 140, 1: 120, 2: 80, 3: 110, 4: 100 } },
    },
  ],
  lockedCells: [
    { r: 0, c: 0 }, { r: 0, c: 1 }, { r: 0, c: 2 }, { r: 0, c: 3 }, { r: 0, c: 4 },
    { r: 1, c: 0 }, { r: 1, c: 1 },
    { r: 2, c: 0 }, { r: 2, c: 1 },
    { r: 3, c: 0 }, { r: 3, c: 1 },
    { r: 5, c: 0 }, { r: 6, c: 0 }, { r: 7, c: 0 }, { r: 8, c: 0 },
  ],
  ui: { showToolbar: false, showFormulaBar: true, showSheetTabs: false },
  xp: { base: 45, bonus: 15 },
  validations: [
    { type: 'cellValue', cell: { r: 1, c: 2 }, expected: 3, stepIndex: 0 },
    { type: 'cellValue', cell: { r: 2, c: 2 }, expected: 3, stepIndex: 0 },
    { type: 'cellValue', cell: { r: 3, c: 2 }, expected: 3, stepIndex: 0 },
    { type: 'cellValue', cell: { r: 1, c: 3 }, expected: 2, stepIndex: 0 },
    { type: 'cellValue', cell: { r: 2, c: 3 }, expected: 5, stepIndex: 0 },
    { type: 'cellValue', cell: { r: 3, c: 3 }, expected: 3, stepIndex: 0 },
    { type: 'cellFormula', cell: { r: 1, c: 4 }, expected: 'B2*C2*D2', stepIndex: 1 },
    { type: 'cellFormula', cell: { r: 2, c: 4 }, expected: 'B3*C3*D3', stepIndex: 2 },
    { type: 'cellFormula', cell: { r: 3, c: 4 }, expected: 'B4*C4*D4', stepIndex: 2 },
    { type: 'cellFormula', cell: { r: 5, c: 4 }, expected: 'SUMME(D2:D4)', stepIndex: 3 },
    { type: 'cellFormula', cell: { r: 6, c: 4 }, expected: 'SUMME(E2:E4)', stepIndex: 3 },
    { type: 'cellFormula', cell: { r: 7, c: 4 }, expected: 'E7/E6', stepIndex: 3 },
    { type: 'cellFormula', cell: { r: 8, c: 4 }, expected: 'MIN(B2:B4)', stepIndex: 3 },
  ],
};
