export default {
  id: 'A-L4-EX3',
  trackId: 'avm',
  levelId: 4,
  order: 3,
  titleKey: 'level4.ex3.title',
  storyKey: 'level4.ex3.story',
  steps: ['level4.ex3.step1', 'level4.ex3.step2', 'level4.ex3.step3', 'level4.ex3.step4'],
  hints: ['level4.ex3.hint1', 'level4.ex3.hint2'],
  initialData: [
    {
      name: 'Sheet1',
      order: 0,
      row: 10,
      column: 5,
      celldata: [
        { r: 0, c: 0, v: { v: 'Produkt', m: 'Produkt', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 0, c: 1, v: { v: 'Preis (€)', m: 'Preis (€)', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 0, c: 2, v: { v: 'Rabatt (%)', m: 'Rabatt (%)', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 0, c: 3, v: { v: 'Ersparnis (€)', m: 'Ersparnis (€)', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 0, c: 4, v: { v: 'Endpreis (€)', m: 'Endpreis (€)', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 1, c: 0, v: { v: 'Lampe', m: 'Lampe', ct: { fa: 'General', t: 's' } } },
        { r: 2, c: 0, v: { v: 'Teppich', m: 'Teppich', ct: { fa: 'General', t: 's' } } },
        { r: 3, c: 0, v: { v: 'Regal', m: 'Regal', ct: { fa: 'General', t: 's' } } },
        { r: 5, c: 0, v: { v: 'Gesamt', m: 'Gesamt', ct: { fa: 'General', t: 's' }, bl: 1 } },
      ],
      config: { columnlen: { 0: 100, 1: 90, 2: 90, 3: 110, 4: 100 } },
    },
  ],
  lockedCells: [
    { r: 0, c: 0 }, { r: 0, c: 1 }, { r: 0, c: 2 }, { r: 0, c: 3 }, { r: 0, c: 4 },
    { r: 1, c: 0 }, { r: 2, c: 0 }, { r: 3, c: 0 }, { r: 5, c: 0 },
  ],
  ui: { showToolbar: false, showFormulaBar: true, showSheetTabs: false },
  xp: { base: 35, bonus: 15 },
  validations: [
    { type: 'cellValue', cell: { r: 1, c: 1 }, expected: 40, stepIndex: 0 },
    { type: 'cellValue', cell: { r: 1, c: 2 }, expected: 20, stepIndex: 0 },
    { type: 'cellFormula', cell: { r: 1, c: 3 }, expected: 'B2*C2/100', stepIndex: 1 },
    { type: 'cellFormula', cell: { r: 1, c: 4 }, expected: 'B2-D2', stepIndex: 2 },
    { type: 'cellFormula', cell: { r: 2, c: 3 }, expected: 'B3*C3/100', stepIndex: 2 },
    { type: 'cellFormula', cell: { r: 2, c: 4 }, expected: 'B3-D3', stepIndex: 2 },
    { type: 'cellFormula', cell: { r: 3, c: 3 }, expected: 'B4*C4/100', stepIndex: 2 },
    { type: 'cellFormula', cell: { r: 3, c: 4 }, expected: 'B4-D4', stepIndex: 2 },
    { type: 'cellFormula', cell: { r: 5, c: 4 }, expected: 'SUMME(E2:E4)', stepIndex: 3 },
  ],
};
