export default {
  id: 'L1-EX4',
  levelId: 1,
  order: 4,
  titleKey: 'level1.ex4.title',
  storyKey: 'level1.ex4.story',
  steps: ['level1.ex4.step1', 'level1.ex4.step2', 'level1.ex4.step3', 'level1.ex4.step4'],
  hints: ['level1.ex4.hint1', 'level1.ex4.hint2'],
  initialData: [
    {
      name: 'Sheet1',
      order: 0,
      row: 12,
      column: 4,
      celldata: [
        { r: 0, c: 0, v: { v: 'Artikel', m: 'Artikel', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 0, c: 1, v: { v: 'Preis (\u20AC)', m: 'Preis (\u20AC)', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 1, c: 0, v: { v: 'Reis', m: 'Reis', ct: { fa: 'General', t: 's' } } },
        { r: 1, c: 1, v: { v: 1.99, m: '1,99', ct: { fa: 'General', t: 'n' } } },
        { r: 2, c: 0, v: { v: 'Nudeln', m: 'Nudeln', ct: { fa: 'General', t: 's' } } },
        { r: 2, c: 1, v: { v: 0.89, m: '0,89', ct: { fa: 'General', t: 'n' } } },
        { r: 3, c: 0, v: { v: 'Öl', m: 'Öl', ct: { fa: 'General', t: 's' } } },
        { r: 3, c: 1, v: { v: 2.49, m: '2,49', ct: { fa: 'General', t: 'n' } } },
        { r: 4, c: 0, v: { v: 'Salz', m: 'Salz', ct: { fa: 'General', t: 's' } } },
        { r: 4, c: 1, v: { v: 0.59, m: '0,59', ct: { fa: 'General', t: 'n' } } },
        { r: 5, c: 0, v: { v: 'Gesamt', m: 'Gesamt', ct: { fa: 'General', t: 's' }, bl: 1 } },
        { r: 5, c: 1, v: { v: 5.96, m: '5,96', ct: { fa: 'General', t: 'n' }, f: '=SUM(B2:B5)' } },
      ],
      config: { columnlen: { 0: 150, 1: 100, 2: 100, 3: 100 } },
    },
  ],
  lockedCells: [
    { r: 0, c: 0 }, { r: 0, c: 1 },
    { r: 1, c: 0 }, { r: 1, c: 1 },
    { r: 2, c: 0 }, { r: 2, c: 1 },
    { r: 3, c: 0 }, { r: 3, c: 1 },
    { r: 4, c: 0 }, { r: 4, c: 1 },
    { r: 5, c: 0 }, { r: 5, c: 1 },
  ],
  ui: { showToolbar: false, showFormulaBar: true, showSheetTabs: false },
  xp: { base: 20, bonus: 10 },
  validations: [
    { type: 'cellValue', cell: { r: 7, c: 0 }, expected: 'Budget', caseInsensitive: true, stepIndex: 0 },
    { type: 'cellValue', cell: { r: 7, c: 1 }, expected: 10, stepIndex: 1 },
    { type: 'cellValue', cell: { r: 8, c: 0 }, expected: 'Rest', caseInsensitive: true, stepIndex: 2 },
    { type: 'cellFormula', cell: { r: 8, c: 1 }, expected: 'B8-B6', stepIndex: 3 },
  ],
};
